country_name: "malawi"
iso3_code: "MWI"
iso2_code: "MW"
path_admin0_shp: "mwi_adm_nso_20181016_shp/mwi_admbnda_adm0_nso_20181016.shp" #downloaded from https://data.humdata.org/dataset/malawi-administrative-level-0-3-boundaries
path_admin1_shp: "mwi_adm_nso_20181016_shp/mwi_admbnda_adm1_nso_20181016.shp" #downloaded from https://data.humdata.org/dataset/malawi-administrative-level-0-3-boundaries
path_admin2_shp: "mwi_adm_nso_20181016_shp/mwi_admbnda_adm2_nso_20181016.shp" #downloaded from https://data.humdata.org/dataset/malawi-administrative-level-0-3-boundaries
shp_adm0c: "ADM0_EN"
shp_adm1c: "ADM1_EN"
shp_adm2c: "ADM2_EN"

foodinsecurity:
  region: "southern-africa"
  regioncode: "SA"
  #no data available for 2018-10 but there is for 2018-12
  #no data availabele for 2012-07. Removing here cause else assigning values due to borders and different shapefiles
  fewsnet_dates_add: ["201812"]
  fewsnet_dates_remove: ["201207", "201810", "202008"]
  pop_filename: "mwi_pop_adm2_32_districts.csv" #downloaded from https://data.humdata.org/search?q=malawi+population&ext_search_source=main-nav
  pop_col: "p2019pop"
  adm0c_pop: "ADM0_EN"
  adm1c_pop: "ADM1_EN"
  adm2c_pop: "ADM2_EN32"
  #population data -- admin boundaries mapping
  pop_bound_adm1_mapping: {}
  pop_bound_adm2_mapping: {}
  #globalIPC -- admin boundaries mapping
  globalipc_adm_mapping:
    Blantyre city: Blantyre City
    Chikhwawa: Chikwawa
    Lilongwe city: Lilongwe City
    Mzuzu city: Mzuzu City
    Nkhata bay: Nkhata Bay
    Zomba city: Zomba City

climate:
  rainy_start_month: 10
  rainy_end_month: 4

glofas:
  stations:
    1:
      name: "glofas_1"
      lat: -16.55
      long: 35.15
    2:
      name: "glofas_2"
      lat: -16.25
      long: 34.95
  leadtimes: [5, 10, 15, 20, 25, 30]
