---
title: "Analysing CHIRPS data for Flood Trigger Development"
output: md_document
---

## Rainfall Analysis

Reading data from shapefile to get river basin bounds:

```{r intro, echo=FALSE, warning = FALSE, message=FALSE, results='hide'}
filePath <- paste0(Sys.getenv("AA_DATA_DIR"), "/public/processed/npl/chirps/")
options(scipen = 100000)
    
# libraries
library(tidyverse)
library(sf)
library(tidyquant)
library(extRemes)
library(tseries)
library(ncdf4)
library(raster)

# reading in shapefile
nplRBSF <- st_read(paste0(Sys.getenv("AA_DATA_DIR"), "/private/exploration/npl/unrco/shapefiles/Major_River_Basins.shp"))
nplWSSF <- st_read(paste0(Sys.getenv("AA_DATA_DIR"), "/private/exploration/npl/unrco/shapefiles/Major_watershed.shp"))

# reading in historical floods
NPLHistFloods <- readxl::read_xlsx(paste0(Sys.getenv("AA_DATA_DIR"), "/private/exploration/npl/unrco/NepalHistoricalFlood1971-2020.xlsx"))

# function for reading in files 
read_files <- function(filePath, fileName){
    ncObj <- nc_open(paste0(filePath, fileName))
    # Karnali
    KarnaliBox <- nplRBSF %>%
        filter(Major_Basi == "Karnali River Basin") %>%
        extent()
    
    KarBoxXMin <- which.min(abs(KarnaliBox[1] - round(ncvar_get(ncObj, "X"), 3)))
    KarBoxXMax <- which.min(abs(KarnaliBox[2] - round(ncvar_get(ncObj, "X"), 3)))
    KarBoxXLen <- KarBoxXMax - KarBoxXMin + 1
    KarBoxYMin <- which.min(abs(KarnaliBox[3] - round(ncvar_get(ncObj, "Y"), 3)))
    KarBoxYMax <- which.min(abs(KarnaliBox[4] - round(ncvar_get(ncObj, "Y"), 3)))
    KarBoxYLen <- KarBoxYMin - KarBoxYMax + 1
    KarDataCube <- ncvar_get(ncObj, "precipitation", 
                             start = c(KarBoxXMin, KarBoxYMax, 1), 
                             count = c(KarBoxXLen, KarBoxYLen, 1)) %>%
        data.frame() %>%
        bind_cols(paste0(round(ncvar_get(ncObj, "X")[KarBoxXMin:KarBoxXMax], 3), "E")) %>%
        setNames(c(paste0(round(ncvar_get(ncObj, "Y")[KarBoxYMax:KarBoxYMin], 3), "N"), "Longitude")) %>%
        gather(key = "Latitude", value = "precipitation", -Longitude) %>%
        mutate(Date = as.Date(str_extract(ncObj$filename,"(?<=daily_).+(?=_r0.05)"), format = "%Y_%m_%d"), 
               Basin = "Karnali River Basin")
    
    # Koshi
    KoshiBox <- nplWSSF %>%
        filter(WSH_NME == "Saptakoshi Watershed") %>%
        extent()
    
    KoshBoxXMin <- which.min(abs(KoshiBox[1] - round(ncvar_get(ncObj, "X"), 3)))
    KoshBoxXMax <- which.min(abs(KoshiBox[2] - round(ncvar_get(ncObj, "X"), 3)))
    KoshBoxXLen <- KoshBoxXMax - KoshBoxXMin + 1
    KoshBoxYMin <- which.min(abs(KoshiBox[3] - round(ncvar_get(ncObj, "Y"), 3)))
    KoshBoxYMax <- which.min(abs(KoshiBox[4] - round(ncvar_get(ncObj, "Y"), 3)))
    KoshBoxYLen <- KoshBoxYMin - KoshBoxYMax + 1
    KoshDataCube <- ncvar_get(ncObj, "precipitation", 
                              start = c(KoshBoxXMin, KoshBoxYMax, 1), 
                              count = c(KoshBoxXLen, KoshBoxYLen, 1)) %>%
        data.frame() %>%
        bind_cols(paste0(round(ncvar_get(ncObj, "X")[KoshBoxXMin:KoshBoxXMax], 3), "E")) %>%
        setNames(c(paste0(round(ncvar_get(ncObj, "Y")[KoshBoxYMax:KoshBoxYMin], 3), "N"), "Longitude")) %>%
        gather(key = "Latitude", value = "precipitation", -Longitude) %>%
        mutate(Date = as.Date(str_extract(ncObj$filename,"(?<=daily_).+(?=_r0.05)"), format = "%Y_%m_%d"), 
               Basin = "Saptakoshi Watershed")
    # close
    nc_close(ncObj)
    # data object
    return(bind_rows(KarDataCube, KoshDataCube))
}


# chirps data frame
chirpsData <- list.files(filePath, pattern = "*.nc") %>%
    map_df(~ read_files(filePath, .)) 

```

```{r}
# rolling sum
# aggregate all grids into one and find mean
# rolling sum is assigned to last day of window
n = 10
AggNational <- chirpsData %>%
    group_by(Date, Basin) %>%
    summarise(rfe = mean(precipitation)) %>%
    group_by(Basin) %>%
    mutate(rollsum = c(rep(0, n-1), rollapplyr(rfe, n, sum))) %>%
    ungroup()
    
# getting top month every year
AggNational2 <- AggNational %>%
    mutate(Year = substr(Date, 1, 4)) %>%
    group_by(Year, Basin) %>%
    top_n(1, rollsum)

ggplot(data = AggNational2, aes(x = Year, y = rollsum, fill = Basin)) + 
    geom_bar(stat="identity", position = "dodge") + 
    theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1)) + 
    ggtitle("CHIRPS Maximum 10-day Rolling Sum of Precipitation with the Associated Month") +
    xlab("Month") + 
    ylab("Maximum 10-day Rolling Sum(mm)")

# checking for stationarity

adf.test(AggNational$rollsum[AggNational$Basin == "Karnali River Basin"]) # reject H0 and say series is stationary at alpha = 0.05
adf.test(AggNational$rollsum[AggNational$Basin == "Saptakoshi Watershed"]) # reject H0 and say series is stationary at alpha = 0.05

returnValues2 <- AggNational2 %>%
    group_by(Basin) %>%
    summarise(returnyr2 = return.level(fevd(x = rollsum), return.period = 2), 
              returnyr5 = return.level(fevd(x = rollsum), return.period = 5), 
              returnyr10 = return.level(fevd(x = rollsum), return.period = 10))

plot(fevd(x = AggNational2$rollsum[AggNational2$Basin == "Karnali River Basin"]))
plot(fevd(x = AggNational2$rollsum[AggNational2$Basin == "Saptakoshi Watershed"]))

ggplot(data = AggNational2, aes(x = Date, y = rollsum, group = Basin)) + 
    geom_line(aes(colour = Basin)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues2[2,"returnyr2"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[2,"returnyr2"]), 
                  label = "RP: 2", vjust = -1)) +
    geom_hline(aes(yintercept = as.numeric(returnValues2[1,"returnyr2"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[1,"returnyr2"]), 
                  label = "RP: 2", vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues2[2,"returnyr5"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[2,"returnyr5"]), 
                  label = "RP: 5", vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues2[1,"returnyr5"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[1,"returnyr5"]), 
                  label = "RP: 5", vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues2[2,"returnyr10"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[2,"returnyr10"]), 
                  label = "RP: 10", vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues2[1,"returnyr10"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues2[1,"returnyr10"]), 
                  label = "RP: 10", vjust = -1)) + 
    ggtitle("Maximum 10-day Rolling Sums Per Year with Return Periods") + 
    ylab("Rolling Sums(mm)")

# extracting the return period
mrlplot(AggNational$rollsum[AggNational$Basin == "Karnali River Basin"], main="Mean Residual Life Plot: Karnali River Basin")
mrlplot(AggNational$rollsum[AggNational$Basin == "Saptakoshi Watershed"], main="Mean Residual Life Plot: Saptakoshi Watershed")

threshrange.plot(AggNational$rollsum[AggNational$Basin == "Karnali River Basin"], r = c(0, 100), nint = 25)
threshrange.plot(AggNational$rollsum[AggNational$Basin == "Saptakoshi Watershed"], r = c(0, 150), nint = 25)

returnValues <- AggNational %>%
    group_by(Basin) %>%
    summarise(returnyr2 = return.level(fevd(x = rollsum, method = "MLE", type="GP", 
                                            threshold = 50), return.period = 2), 
              returnyr5 = return.level(fevd(x = rollsum, method = "MLE", type="GP", 
                                            threshold = 50), return.period = 5), 
              returnyr10 = return.level(fevd(x = rollsum, method = "MLE", type="GP", 
                                             threshold = 50), return.period = 10))

ggplot(data = AggNational, aes(x = Date, y = rollsum, group = Basin)) + 
    geom_line(aes(colour = Basin)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues[1,"returnyr2"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[1,"returnyr2"]), 
                  label = paste0("RP: 2-", round(as.numeric(returnValues[1,"returnyr2"]))),
                  vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues[2,"returnyr2"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[2,"returnyr2"]), 
                  label = paste0("RP: 2-", round(as.numeric(returnValues[2,"returnyr2"]))),
                  vjust = -1)) +
    geom_hline(aes(yintercept = as.numeric(returnValues[1,"returnyr5"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[1,"returnyr5"]), 
                  label = paste0("RP: 5-", round(as.numeric(returnValues[1,"returnyr5"]))),
                  vjust = -1)) +
    geom_hline(aes(yintercept = as.numeric(returnValues[2,"returnyr5"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[2,"returnyr5"]), 
                  label = paste0("RP: 5-", round(as.numeric(returnValues[2,"returnyr5"]))),
                  vjust = -1)) + 
    geom_hline(aes(yintercept = as.numeric(returnValues[1,"returnyr10"]), colour = Basin[1])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[1,"returnyr10"]), 
                  label = paste0("RP: 10-", round(as.numeric(returnValues[1,"returnyr10"]))), 
                  vjust = -1)) +
    geom_hline(aes(yintercept = as.numeric(returnValues[2,"returnyr10"]), colour = Basin[2])) + 
    geom_text(aes(as.Date("1980-01-01"), as.numeric(returnValues[2,"returnyr10"]), 
                  label = paste0("RP: 10-", round(as.numeric(returnValues[2,"returnyr10"]))),
                  vjust = -1)) + 
    ggtitle("10-day Rolling Sums with Return Periods in Years") + 
    ylab("Rolling Sums(mm)")

```

```{r}
# comparing historical values with return values
# dates where value was exceeded
AggNational3 <- AggNational %>%
    mutate(thresh2Yr = rollsum >= unlist(returnValues[,"returnyr2"])) %>%
    mutate(thresh5Yr = rollsum >= unlist(returnValues[,"returnyr5"])) %>%
    mutate(thresh10Yr = rollsum >= unlist(returnValues[,"returnyr10"])) %>%
    filter(thresh2Yr)

summary(ecdf(unique(NPLHistFloods$`Affected Family`)))
NPLHistFloodsWorst <- NPLHistFloods %>%
    filter(`Affected Family` >= 5000)

```

