iso3_code: uga
iso2_code: ug
path_admin0_shp: uga_admbnda_ubos_20200824_shp/uga_admbnda_adm0_ubos_20200824.shp #Shapefiles downloaded from https://data.humdata.org/dataset/cod-ab-uga
path_admin1_shp: uga_admbnda_ubos_20200824_shp/uga_admbnda_adm1_ubos_20200824.shp
path_admin2_shp: uga_admbnda_ubos_20200824_shp/uga_admbnda_adm2_ubos_20200824.shp