# country specific parameters
ETH:
  country_name: "ethiopia"
  iso2_code: "ET"
  region: "east-africa"
  regioncode: "EA"
  path_admin2_shp: "ET_Admin_OCHA_2020/eth_admbnda_adm2_csa_bofed_20201008.shp" #downloaded from https://data.humdata.org/dataset/ethiopia-cod-ab
  fewsnet_dates: ["200907","200910","201001","201004","201007","201010","201101","201104","201107","201110","201201",
  "201204","201207","201210","201301","201304","201307","201310","201401","201404","201407","201410","201501","201504",
  "201507","201510","201602","201606","201610","201702","201706","201710","201802","201806","201810",
  "201902","201906","201910","202002","202006","202008","202009","202010"]
  shp_adm0c: "ADM0_EN"
  shp_adm1c: "ADM1_EN"
  shp_adm2c: "ADM2_EN"
  pop_filename: "Population_OCHA_2020/eth_admpop_adm2_20201028.csv" #downloaded from https://data.humdata.org/dataset/ethiopia-population-data-_-admin-level-0-3
  pop_col: "Total"
  adm1c_pop: "ADM1_EN"
  adm2c_pop: "ADM2_EN"
  admin1_mapping: {}
  admin2_mapping:
    Etang Special: Etang Special woreda
    Zone 4  (Fantana Rasu): Zone 4 (Fantana Rasu)
    Halaba Special: Halaba
  ipc_path: "GlobalIPC/GlobalIPC_newcolumnnames.xlsx"
  replace_dict:
    Oromiya: Oromia
    SNNPR: SNNP

MWI:
  country_name: "malawi"
  iso2_code: "MW"
  region: "southern-africa"
  regioncode: "SA"
  path_admin2_shp: "mwi_adm_nso_20181016_shp/mwi_admbnda_adm2_nso_20181016.shp" #downloaded from https://data.humdata.org/dataset/malawi-administrative-level-0-3-boundaries
  #no data available for 2018-10 but there is for 2018-12
  #no data availabele for 2012-07. Removing here cause else assigning values due to borders and different shapefiles
  fewsnet_dates: [ "200907","200910","201001","201004","201007","201010","201101","201104","201107","201110","201201",
                   "201204","201210","201301","201304","201307","201310","201401","201404","201407","201410","201501","201504",
                   "201507","201510","201602","201606","201610","201702","201706","201710","201802","201806","201812",
                   "201902","201906","201910","202002","202006","202008","202010"]
  shp_adm0c: "ADM0_EN"
  shp_adm1c: "ADM1_EN"
  shp_adm2c: "ADM2_EN"
  pop_filename: "Population_OCHA_2018/mwi_pop_adm2_32_districts.csv" #downloaded from https://data.humdata.org/search?q=malawi+population&ext_search_source=main-nav
  pop_col: "p2019pop"
  adm1c_pop: "ADM1_EN"
  adm2c_pop: "ADM2_EN32"
  #population data -- admin boundaries mapping
  admin1_mapping: {}
  admin2_mapping: {}
  ipc_path: "GlobalIPC/GlobalIPC_newcolumnnames.xlsx"
  #globalIPC -- admin boundaries mapping
  replace_dict:
    Blantyre city: Blantyre City
    Chikhwawa: Chikwawa
    Lilongwe city: Lilongwe City
    Mzuzu city: Mzuzu City
    Nkhata bay: Nkhata Bay
    Zomba city: Zomba City

SOM:
  country_name: "somalia"
  iso2_code: "SO"
  region: "east-africa"
  regioncode: "EA"
  path_admin2_shp: "Som_Admbnda_Adm2_UNDP.shp" #downloaded from https://data.humdata.org/dataset/ec140a63-5330-4376-a3df-c7ebf73cfc3c/resource/6f42e9ce-bbca-4c0d-a3e6-85efc9298c3c/download/som_adm_undp_shp.zip
  fewsnet_dates: [ "200907","200910","201001","201004","201007","201010","201101","201104","201107","201110","201201",
                   "201204","201210","201301","201304","201307","201310","201401","201404","201407","201410","201501","201504",
                   "201507","201510","201602","201606","201610","201702","201706","201710","201802","201806","201812",
                   "201902","201906","201910","202002","202006","202008","202010"]
  shp_adm0c: "ADM0_EN"
  shp_adm1c: "ADM1_EN"
  shp_adm2c: "ADM2_EN"
  pop_filename: "som_pplp_adm2.csv" #downloaded from https://data.humdata.org/dataset/6cac9c64-2716-4809-9e82-440839d421f6/resource/a63d9729-c8fa-4456-a3fd-11034dd2117b/download/som_pplp_adm2.csv
  pop_col: "Pop2014UNFPA"
  adm1c_pop: "admin1Name_en"
  adm2c_pop: "Admin2Name_en"
  admin1_mapping: {}
  admin2_mapping: {}