DIRS:
  adm_dir: "data/ADM_Shp"
  data_dir: "data/FE_Results/June_Aug"
  gee_dir: "data/GEE_Output/June_Aug"
  plot_dir: "results/summary"
FILES:
  adm_shp: 'data/ADM_Shp/selected_distict_mauza.shp'
  river_shp: 'data/ADM_Shp/river_extent.shp'
PARAMS:
  crs: 'EPSG:32646'
  adm: 'MAUZ'