iso2_code: mg

path_admin0_shp: mdg_admbnda_adm0_BNGRC_OCHA_20181031.shp
path_admin1_shp: mdg_admbnda_adm1_BNGRC_OCHA_20181031.shp
path_admin2_shp: mdg_admbnda_adm2_BNGRC_OCHA_20181031.shp
path_admin3_shp: mdg_admbnda_adm3_BNGRC_OCHA_20181031.shp
path_admin4_shp: mdg_admbnda_adm4_BNGRC_OCHA_20181031.shp

shp_adm0c: ADM0_PCODE
shp_adm1c: ADM1_PCODE
shp_adm2c: ADM2_PCODE
shp_adm3c: ADM3_PCODE
shp_adm4c: ADM4_PCODE