country_name: "somalia"
iso3_code: "som"
iso2_code: "so"
path_admin0_shp: "som_adm_undp_shp/Som_Admbnda_Adm0_UNDP.shp" #downloaded from https://data.humdata.org/dataset/ec140a63-5330-4376-a3df-c7ebf73cfc3c/resource/6f42e9ce-bbca-4c0d-a3e6-85efc9298c3c/download/som_adm_undp_shp.zip
path_admin1_shp: "som_adm_undp_shp/Som_Admbnda_Adm1_UNDP.shp" #downloaded from https://data.humdata.org/dataset/ec140a63-5330-4376-a3df-c7ebf73cfc3c/resource/6f42e9ce-bbca-4c0d-a3e6-85efc9298c3c/download/som_adm_undp_shp.zip
path_admin2_shp: "som_adm_undp_shp/Som_Admbnda_Adm2_UNDP.shp" #downloaded from https://data.humdata.org/dataset/ec140a63-5330-4376-a3df-c7ebf73cfc3c/resource/6f42e9ce-bbca-4c0d-a3e6-85efc9298c3c/download/som_adm_undp_shp.zip
shp_adm0c: "admin0Name"
shp_adm1c: "admin1Name"
shp_adm2c: "admin2Name"

foodinsecurity:
  region: "east-africa"
  regioncode: "EA"
  fewsnet_dates_add: ["202008","202011"]
  fewsnet_dates_remove: ["200907"]
  pop_filename: "som_pplp_adm2.csv" #downloaded from https://data.humdata.org/dataset/6cac9c64-2716-4809-9e82-440839d421f6/resource/a63d9729-c8fa-4456-a3fd-11034dd2117b/download/som_pplp_adm2.csv
  pop_col: "Pop2014UNFPA"
  adm0c_pop: "admin0Name_en"
  adm1c_pop: "admin1Name_en"
  adm2c_pop: "Admin2Name_en"
  pop_adm1_mapping: {}
  pop_adm2_mapping:
    Baidoa: Baydhaba
    Bandarbayla: Bandarbeyla
    Baydhaba: Baydhabo