glofas:
  stations:
    Asaraghat:
      lat: 29.15
      lon: 81.55
    Asaraghat_v3:
      lat: 28.95
      lon: 81.45
    Chatara:
      lat: 26.95
      lon: 87.15
    Chatara_v3:
      lat: 26.85
      lon: 87.15
    Chepang:
      lat: 28.25
      lon: 81.85
    Chepang_v3:
      lat: 28.35
      lon: 81.75
    Chisapani:
      lat: 28.75
      lon: 81.25
    Chisapani_v3:
      lat: 28.65
      lon: 81.25
    Dipayal:
      lat: 29.25
      lon: 80.95
    Dipayal_v3:
      lat: 29.25
      lon: 80.95
    Kampughat:
      lat: 26.85
      lon: 86.85
    Kampughat_v3:
      lat: 26.85
      lon: 86.85
    Kusum:
      lat: 27.85
      lon: 82.35
    Kusum_v3:
      lat: 27.95
      lon: 82.15
    Majhitar:
      lat: 27.05
      lon: 87.55
    Majhitar_v3:
      lat: 26.95
      lon: 87.45
    Rai_goan:
      lat: 27.25
      lon: 85.45
    Rai_goan_v3:
      lat: 27.25
      lon: 85.45
    Samajhighat:
      lat: 28.45
      lon: 81.95
    Samajhighat_v3:
      lat: 28.55
      lon: 81.65
    Simle:
      lat: 27.05
      lon: 87.15
    Simle_v3:
      lat: 27.05
      lon: 87.15
    # DHM point added later
    # https://hydrology.gov.np/#/basin/4635?_k=ep79ty
    Kandra:
      lat: 28.7
      lon: 80.9