DIRS:
  adm_dir: "exploration/bangladesh/ADM_Shp"
  data_dir: "exploration/bangladesh/FE_Results/June_Aug"
  gee_dir: "exploration/bangladesh/GEE_Output/June_Aug"
  plot_dir: "exploration/bangladesh/Plots"
FILES:
  # adm_shp: 'exploration/bangladesh/ADM_Shp/selected_distict_mauza.shp'
  adm_shp: 'exploration/bangladesh/ADM_Shp/bgd_admbnda_adm4_bbs_20201113.shp'
  river_shp: 'exploration/bangladesh/ADM_Shp/river_extent.shp'
PARAMS:
  crs: 'EPSG:32646'
  adm: 'ADM4'